version: '3.5'

services:
  forum.api:
    build:
      context: .
      dockerfile: Forum.Api/Dockerfile
    ports:
      - 24111:24111
    environment:
      DB_CONNECTION_STRING: "User ID=api_user;Password=1111;Host=localhost;Port=5432;Database=ForumDb;Pooling=true"
    networks:
      - forum-api-network
    depends_on:
      - postgres-db
    command: [ "./wait-for-it.sh", "postgres-db:5432", "--", "dotnet", "Forum.Api.dll" ]
    
  postgres-db:
    image: postgres
    hostname: localhost
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-api_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1111}
      POSTGRES_DB: ${POSTGRES_DB:-ForumDb}
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - 5432:5432
    networks:
      - forum-api-network
    restart: unless-stopped
    
networks:
  forum-api-network:
    driver: bridge

volumes: 
  postgres-data:
