version: '3.5'

services:
  forum.api:
    image: aspnet-api:latest
    depends_on:
      - "postgres-db"
    build:
      context: .
      dockerfile: Forum.Api/Dockerfile
    ports:
      - "24110:24110"
    environment:
      DB_CONNECTION_STRING: "User ID=api_user;Password=1111;Host=postgres_image;Port=5432;Database=ForumDb;Pooling=true"
    networks:
      - forum-api-network
    
  postgres-db:
    image: postgres
    environment:
      hostname: nextcloud-db
      POSTGRES_USER: ${POSTGRES_USER:-api_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1111}
      POSTGRES_DB: ${POSTGRES_DB:-ForumDb}
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - forum-api-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - forum-api-network
    restart: unless-stopped
    
networks:
  forum-api-network:
    driver: bridge

volumes: 
  postgres-data:
  pgadmin:
