version: '3.5'

services:
  forum.api:
    container_name: ForumApiContainer
    depends_on:
      - postgres-db
    image: 'forumapiapp'
    build:
      context: .
      dockerfile: Forum.Api/Dockerfile
    ports:
      - '24110:24110'
    environment:
      DB_CONNECTION_STRING: "User ID=webappuser;Password=1234567890;Host=postgres-db;Port=5432;Database=ForumDb;Pooling=true"
      ASPNETCORE_HTTP_PORTS: 24110
    networks:
      - forum-api-network

  postgres-db:
    container_name: PostgresContainer
    hostname: 'postgres-db'
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: webappuser
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: ForumDb
      PGDATA: /data/postgres
    volumes:
      - 'postgres-data:/data/postgres'
    ports:
      - '5432:5432'
    networks:
      - forum-api-network
    restart: unless-stopped
  
  forum.post.api:
    container_name: ForumPostApiContainer
    depends_on:
      - cassandra-db
    image: 'postapiapp'
    build:
      context: .
      dockerfile: Forum.PostApi/Dockerfile
    ports:
      - '24130:24130'
    environment:
      ASPNETCORE_HTTP_PORTS: 24130
    networks:
      - forum-post-api-network
    command: >
      /bin/sh -c "dockerize -wait tcp://cassandra-db:9042 -timeout 2m &&
                 dotnet run"
      
  cassandra-db:
    container_name: CassandraContainer
    image: scylladb/scylla:5.4
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/data/cassandra
    networks:
      - forum-post-api-network
    restart: unless-stopped
    
  broker:
    image: confluentinc/cp-server:7.5.0
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: 'broker:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

networks:
  forum-api-network:
    driver: bridge
  forum-post-api-network:
    driver: bridge
volumes:
  postgres-data:
  pgadmin:
  cassandra-data: 
