version: '3.5'
services:
  forum.api:
    container_name: ForumApiContainer
    depends_on:
      - postgres-db
    image: 'aspnetcoreapp'
    build:
      context: .
      dockerfile: Forum.Api/Dockerfile
    ports:
      - '24110:24110'
    environment:
      DB_CONNECTION_STRING: "User ID=webappuser;Password=1234567890;Host=postgres-db;Port=5432;Database=ForumDb;Pooling=true"
      ASPNETCORE_HTTP_PORTS: 24110
      ASPNETCORE_URLS: "http://*:24110"
    networks:
      - forum-api-network

  postgres-db:
    container_name: PostgresContainer
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: webappuser
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: ForumDb
      PGDATA: /data/postgres
    volumes:
      - 'postgres-data:/data/postgres'
    ports:
      - '127.0.0.1:5432:5432'
    expose:
      - "5432"
    networks:
      - forum-api-network
    restart: unless-stopped
    
  pgadmin:
    container_name: PgAdminContainer
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - forum-api-network
    restart: unless-stopped
    
networks:
  forum-api-network:
    driver: bridge
volumes:
  postgres-data: null
  pgadmin:
